(function () {
  "use strict";
  const questionCore = globalThis.AcidBaseCore;
  const scaffoldCore = globalThis.AcidBaseScaffold;
  const mastery = globalThis.AcidBaseMasteryCore;
  const STORAGE_KEY = "acid-base-mastery-v2";
  const elements = Object.fromEntries(["setupScreen","activityScreen","finishScreen","familyGrid","selectionFeedback","startSession","resumeCard","resumeSummary","resumeSession","discardSession","resetSession","levelBanner","masteryGauge","questionPanel","answerPanel","answerContent","finishGauge","finishStats","newSession"].map((id) => [id, document.getElementById(id)]));
  let session = null;
  let question = null;

  function escapeHtml(value) { return String(value).replace(/[&<>"]/g, (character) => ({ "&":"&amp;", "<":"&lt;", ">":"&gt;", "\"":"&quot;" }[character])); }
  function notationHtml(value) {
    return escapeHtml(value).replace(/10⁻([0-9]+(?:\.[0-9]+)?)/g,"10<sup>−$1</sup>").replace(/pK_a/g,"pK<sub>a</sub>").replace(/K_w/g,"K<sub>w</sub>").replace(/K_a/g,"K<sub>a</sub>").replace(/M_r/g,"M<sub>r</sub>").replace(/V\(((?:[^()]|\([^)]*\))+?)\)/g,"Volume of $1").replace(/c₂\(((?:[^()]|\([^)]*\))+?)\)/g,"[$1]₂").replace(/c\(((?:[^()]|\([^)]*\))+?)\)/g,"[$1]");
  }
  function wrapped(text) { if (!(text.startsWith("(")&&text.endsWith(")"))) return false; let depth=0; for(let i=0;i<text.length;i+=1){if(text[i]==="(")depth+=1;if(text[i]===")")depth-=1;if(depth===0&&i<text.length-1)return false;}return depth===0; }
  function slashAt(text){let r=0,s=0;for(let i=0;i<text.length;i+=1){if(text[i]==="(")r+=1;else if(text[i]===")")r-=1;else if(text[i]==="[")s+=1;else if(text[i]==="]")s-=1;else if(text[i]==="/"&&r===0&&s===0)return i;}return -1;}
  function denominatorEnd(text){let r=0,s=0;for(let i=0;i<text.length;i+=1){if(text[i]==="(")r+=1;else if(text[i]===")")r-=1;else if(text[i]==="[")s+=1;else if(text[i]==="]")s-=1;if(r===0&&s===0){const power=text.startsWith(" × 10",i)&&/[⁻⁺⁰¹²³⁴⁵⁶⁷⁸⁹]/.test(text[i+5]||"");if((text.startsWith(" × ",i)&&!power)||text.startsWith(" + ",i)||text.startsWith(" − ",i))return i;}}return text.length;}
  function renderMath(source, tokenRenderer) { const text=String(source).trim(); if(wrapped(text))return `(${renderMath(text.slice(1,-1),tokenRenderer)})`; const slash=slashAt(text); if(slash<0)return tokenRenderer?tokenRenderer(text):notationHtml(text); const numerator=text.slice(0,slash).trim(),remainder=text.slice(slash+1),end=denominatorEnd(remainder),denominator=remainder.slice(0,end).trim(),suffix=remainder.slice(end); return `<span class="fraction"><span>${renderMath(numerator,tokenRenderer)}</span><span>${renderMath(denominator,tokenRenderer)}</span></span>${suffix?` ${renderMath(suffix,tokenRenderer)}`:""}`; }
  function workingRows(lines){return lines.flatMap((line)=>String(line).split(";")).flatMap((line)=>{const clean=line.trim();if(!clean)return[];const parts=clean.split(" = ");if(parts.length<2)return[{type:"note",text:clean}];return parts.slice(1).map((right,index)=>({type:"equation",left:index===0?parts[0]:"",right}));});}

  function save(){ if(!session)return; try{localStorage.setItem(STORAGE_KEY,JSON.stringify(session));}catch(error){ elements.levelBanner.textContent="Progress cannot be saved in this browser."; } }
  function savedSession(){try{const value=JSON.parse(localStorage.getItem(STORAGE_KEY));return mastery.validateSession(value)?value:null;}catch(error){return null;}}
  function clearSave(){try{localStorage.removeItem(STORAGE_KEY);}catch(error){/* no-op */}}
  function randomSeed(){if(globalThis.crypto?.getRandomValues)return globalThis.crypto.getRandomValues(new Uint32Array(1))[0];return Date.now()>>>0;}

  function renderFamilies(){
    elements.familyGrid.innerHTML=mastery.selectableFamilies().map((family)=>`<label class="family-toggle"><span><span class="family-name">${notationHtml(family.label)}</span><span class="family-levels">Available: ${family.levels.map((level)=>`Level ${level}`).join(", ")}</span></span><input type="checkbox" value="${escapeHtml(family.id)}" ${family.id!=="buffer"?"checked":""}><span class="switch" aria-hidden="true"></span></label>`).join("");
  }

  function showSetup(){elements.setupScreen.hidden=false;elements.activityScreen.hidden=true;elements.finishScreen.hidden=true;renderFamilies();const saved=savedSession();elements.resumeCard.hidden=!saved;if(saved){elements.resumeSummary.textContent=`Level ${saved.level || 1} · ${saved.selectedFamilies.length} calculation ${saved.selectedFamilies.length===1?"family":"families"}`;}}
  function start(selected){try{session=mastery.createSession(selected,randomSeed());mastery.nextQuestion(session);save();showActivity();}catch(error){elements.selectionFeedback.textContent=error.message;}}
  function resume(){session=savedSession();if(!session){showSetup();return;}if(!session.current&&!session.completed)mastery.nextQuestion(session);showActivity();}
  function showActivity(){elements.setupScreen.hidden=true;elements.finishScreen.hidden=true;elements.activityScreen.hidden=false;if(session.completed){showFinish();return;}question=mastery.generateCurrent(session);renderGauge();renderQuestion();save();}

  function statusLabel(status,level){return status==="mastered"?`Level ${level} mastered`:status==="due"?`Level ${level} needs proof`:status==="current"?`Level ${level} current`:`Level ${level} ${status}`;}
  function gaugeHtml(){const families=new Map(mastery.selectableFamilies().map((item)=>[item.id,item]));return session.selectedFamilies.map((id)=>{const family=families.get(id);return `<div class="gauge-row"><div class="gauge-family">${notationHtml(family.label)}</div><div class="gauge-lights">${family.levels.map((level)=>{const status=session.progress[id][level].status;return `<span class="level-light ${status}" aria-label="${statusLabel(status,level)}" title="${statusLabel(status,level)}">${level}</span>`;}).join("")}</div></div>`;}).join("");}
  function renderGauge(){elements.levelBanner.textContent=`Level ${session.level} · ${session.mode==="proof"?"Proof round":"Initial round"}`;elements.masteryGauge.innerHTML=gaugeHtml();}

  function workingEditorMarkup(token,partIndex,number){const label=`Working number ${number} for part ${String.fromCharCode(97+partIndex)}`,standard=scaffoldCore.prefersStandardForm(token.expected)?`<span class="working-standard-entry" hidden><input class="working-mantissa-input" type="text" inputmode="decimal" autocomplete="off" aria-label="${label}, standard-form mantissa"><span>× 10</span><input class="working-exponent-input" type="text" inputmode="numeric" autocomplete="off" aria-label="${label}, standard-form exponent"></span><button class="working-notation-toggle" type="button" data-working-notation-toggle aria-pressed="false" title="Enter this number in standard form">×10ⁿ</button>`:"";return `<span class="working-entry"><span class="working-value-entry" data-working-editor data-mode="decimal" data-expected="${token.expected}" data-tolerance="${token.tolerance}"><input class="working-input" type="text" inputmode="decimal" autocomplete="off" aria-label="${label}">${standard}</span><span class="working-marker"></span></span>`;}
  function scaffoldText(value,partIndex,state){const source=String(value);let cursor=0,html="";for(const token of scaffoldCore.numericTokens(source)){html+=notationHtml(source.slice(cursor,token.index));const number=++state.count;if(number===state.total){html+=`<span class="scaffold-final-slot" data-expected="${state.finalExpected}" data-tolerance="${state.finalTolerance}"><span class="working-marker"></span></span>`;}else{html+=workingEditorMarkup(token,partIndex,number);}cursor=token.index+token.raw.length;}return html+notationHtml(source.slice(cursor));}
  function scaffoldExpression(source,partIndex,state){return renderMath(source,(text)=>scaffoldText(text,partIndex,state));}
  function scaffoldMarkup(lines,index,response){const rows=workingRows(lines);const total=rows.reduce((sum,row)=>sum+(row.type==="equation"?scaffoldCore.numericTokens(row.right).length:0),0);if(!total)return"";const state={count:0,total,finalExpected:response.expected,finalTolerance:response.tolerance};return rows.map((row)=>row.type==="note"?`<p class="math-note">${notationHtml(row.text)}</p>`:`<div class="scaffold-math-row"><span class="math-lhs">${notationHtml(row.left)}</span><span class="math-equals">=</span><span class="math-rhs">${scaffoldExpression(row.right,index,state)}</span></div>`).join("");}
  function responseEditorMarkup(index){
    const saved=session.current.responses[index]||"",mode=session.current.responseModes[index]||"decimal",stored=session.current.standardResponses[index]||{},parsed=mastery.parseStandardParts(saved),mantissa=stored.mantissa??parsed?.mantissa??"",exponent=stored.exponent??parsed?.exponent??"";
    return `<span class="value-entry" data-response-editor="${index}"><input class="response-input decimal-input" id="response-${index}" value="${escapeHtml(saved)}" type="text" inputmode="decimal" autocomplete="off" aria-label="Answer" ${mode==="standard"?"hidden":""}><span class="standard-entry" ${mode!=="standard"?"hidden":""}><input class="mantissa-input" value="${escapeHtml(mantissa)}" type="text" inputmode="decimal" autocomplete="off" aria-label="Standard-form mantissa"><span aria-hidden="true">× 10</span><input class="exponent-input" value="${escapeHtml(exponent)}" type="text" inputmode="numeric" autocomplete="off" aria-label="Standard-form exponent"></span><button class="notation-toggle" type="button" data-notation-toggle="${index}" aria-pressed="${mode==="standard"}" title="${mode==="standard"?"Use a single number field":"Enter in standard form"}">${mode==="standard"?"123":"×10ⁿ"}</button></span>`;
  }
  function responseMarkup(response,index){const scaffold=scaffoldMarkup(question.answerParts[index],index,response);return `<section class="response-row" data-part="${index}"><div class="response-prompt"><label for="response-${index}"><span class="part-label">${String.fromCharCode(97+index)}</span><span>${notationHtml(response.prompt)}</span></label>${scaffold?`<button class="scaffold-toggle" type="button" data-scaffold-toggle="${index}" aria-expanded="false" aria-controls="scaffold-${index}" aria-label="Show working framework for part ${String.fromCharCode(97+index)}">?</button>`:""}</div>${scaffold?`<div class="working-scaffold" id="scaffold-${index}" hidden>${scaffold}<div class="scaffold-actions"><button type="button" data-check-scaffold="${index}">Check working</button><p class="scaffold-feedback" aria-live="polite"></p></div></div>`:""}<div class="answer-line"><span class="symbol">${notationHtml(response.symbol)} =</span>${responseEditorMarkup(index)}<span class="unit">${notationHtml(response.unit||"")}</span></div><p class="response-feedback" aria-live="polite"></p></section>`;}

  function renderQuestion(){
    session.current.responseModes=session.current.responseModes||[];
    session.current.standardResponses=session.current.standardResponses||[];
    const rows=question.rows.map((item)=>`<tr><th>${notationHtml(item.label)}</th><td>${notationHtml(item.value)}</td></tr>`).join("");
    elements.questionPanel.innerHTML=`<div class="question-header"><div><p class="question-meta">LEVEL ${session.current.level} · ${notationHtml(question.familyLabel).toUpperCase()}</p><h2 class="question-type">${notationHtml(question.templateLabel)}</h2></div>${session.current.kind==="proof"?'<span class="proof-chip">PROOF QUESTION</span>':""}</div><p class="question-intro">${notationHtml(question.intro)}</p><table class="data-table"><tbody>${rows}</tbody></table><p class="rounding-note">Give pH and pK<sub>a</sub> values to 2 decimal places. Give other numerical answers to 3 significant figures unless exact.</p><p class="scaffold-key"><span>?</span>Using a working framework means this question will return later for proof.</p><div class="response-list">${question.responses.map(responseMarkup).join("")}</div><div class="action-row"><button class="primary" id="checkAnswer" type="button">Check answers</button><p class="check-summary" id="checkSummary" aria-live="polite"></p><button class="continue-button" id="continueButton" type="button" hidden>Continue</button></div>`;
    const reviewId=questionCore.formatQuestionId(session.current.seed);
    const review=document.createElement('p');review.className='question-meta';
    review.textContent='Review ID // '+reviewId;
    const sidebar=document.getElementById('masteryGauge').parentElement;
    sidebar.querySelector('[data-review-id]')?.remove();review.dataset.reviewId=reviewId;sidebar.prepend(review);
    elements.answerPanel.hidden=true;elements.answerPanel.open=false;
    elements.questionPanel.querySelectorAll("[data-scaffold-toggle]").forEach((button)=>button.addEventListener("click",()=>openScaffold(Number(button.dataset.scaffoldToggle),true)));
    elements.questionPanel.querySelectorAll("[data-check-scaffold]").forEach((button)=>button.addEventListener("click",()=>checkScaffold(button)));
    elements.questionPanel.querySelectorAll("[data-working-editor]").forEach((editor)=>wireWorkingEditor(editor));
    elements.questionPanel.querySelectorAll("[data-working-notation-toggle]").forEach((button)=>button.addEventListener("click",()=>toggleWorkingNotation(button)));
    elements.questionPanel.querySelectorAll("[data-response-editor]").forEach((editor)=>wireResponseEditor(editor));
    elements.questionPanel.querySelectorAll("[data-notation-toggle]").forEach((button)=>button.addEventListener("click",()=>toggleNotation(Number(button.dataset.notationToggle))));
    document.getElementById("checkAnswer").addEventListener("click",checkAnswers);
    document.getElementById("continueButton").addEventListener("click",()=>{mastery.continueSession(session);showActivity();});
    if(session.current.firstSubmitted)restoreAttempt();
    [...new Set([...(session.current.scaffoldParts||[]),...(session.current.incorrectParts||[])])].forEach((index)=>openScaffold(index,false));
  }

  function responseValue(index){if((session.current.responseModes[index]||"decimal")==="standard"){const values=session.current.standardResponses[index]||{};return mastery.standardValue(values.mantissa,values.exponent);}return elements.questionPanel.querySelector(`[data-response-editor="${index}"] .decimal-input`)?.value||session.current.responses[index]||"";}
  function wireResponseEditor(editor){const index=Number(editor.dataset.responseEditor),decimal=editor.querySelector(".decimal-input"),mantissa=editor.querySelector(".mantissa-input"),exponent=editor.querySelector(".exponent-input");decimal.addEventListener("input",()=>{session.current.responses[index]=decimal.value;clearResponseMark(index);save();});const updateStandard=()=>{const split=mastery.parseStandardParts(mantissa.value);if(split){mantissa.value=split.mantissa;exponent.value=split.exponent;}session.current.standardResponses[index]={mantissa:mantissa.value,exponent:exponent.value};session.current.responses[index]=mastery.standardValue(mantissa.value,exponent.value);clearResponseMark(index);save();};mantissa.addEventListener("input",updateStandard);exponent.addEventListener("input",updateStandard);}
  function toggleNotation(index){const editor=elements.questionPanel.querySelector(`[data-response-editor="${index}"]`),decimal=editor.querySelector(".decimal-input"),standard=editor.querySelector(".standard-entry"),mantissa=editor.querySelector(".mantissa-input"),exponent=editor.querySelector(".exponent-input"),button=editor.querySelector(".notation-toggle"),toStandard=(session.current.responseModes[index]||"decimal")!=="standard";if(toStandard){let parts=mastery.parseStandardParts(decimal.value);if(!parts&&decimal.value.trim()&&Number.isFinite(questionCore.enteredNumber(decimal.value))){const value=questionCore.enteredNumber(decimal.value),power=value===0?0:Math.floor(Math.log10(Math.abs(value)));parts={mantissa:String(Number((value/10**power).toPrecision(12))),exponent:String(power)};}if(parts){mantissa.value=parts.mantissa;exponent.value=parts.exponent;}session.current.responseModes[index]="standard";session.current.standardResponses[index]={mantissa:mantissa.value,exponent:exponent.value};decimal.hidden=true;standard.hidden=false;button.textContent="123";button.title="Use a single number field";button.setAttribute("aria-pressed","true");mantissa.focus();}else{const combined=mastery.standardValue(mantissa.value,exponent.value);if(combined)decimal.value=combined;session.current.responses[index]=combined||decimal.value;session.current.responseModes[index]="decimal";standard.hidden=true;decimal.hidden=false;button.textContent="×10ⁿ";button.title="Enter in standard form";button.setAttribute("aria-pressed","false");decimal.focus();}clearResponseMark(index);save();}
  function workingEditorValue(editor){return editor.dataset.mode==="standard"?scaffoldCore.standardValue(editor.querySelector(".working-mantissa-input")?.value,editor.querySelector(".working-exponent-input")?.value):editor.querySelector(".working-input")?.value||"";}
  function clearWorkingEditor(editor){editor.classList.remove("working-correct","working-incorrect");editor.querySelectorAll("input").forEach((input)=>input.removeAttribute("aria-invalid"));const marker=editor.nextElementSibling;if(marker){marker.textContent="";marker.className="working-marker";}const feedback=editor.closest(".working-scaffold")?.querySelector(".scaffold-feedback");if(feedback)feedback.textContent="";}
  function wireWorkingEditor(editor){editor.querySelectorAll("input").forEach((input)=>input.addEventListener("input",()=>clearWorkingEditor(editor)));}
  function toggleWorkingNotation(button){const editor=button.closest("[data-working-editor]"),decimal=editor.querySelector(".working-input"),standard=editor.querySelector(".working-standard-entry"),mantissa=editor.querySelector(".working-mantissa-input"),exponent=editor.querySelector(".working-exponent-input"),toStandard=editor.dataset.mode!=="standard";if(toStandard){const entered=decimal.value.trim();let parts=scaffoldCore.parseStandardParts(entered);if(!parts&&entered&&Number.isFinite(questionCore.enteredNumber(entered)))parts=scaffoldCore.standardParts(questionCore.enteredNumber(entered));if(parts){mantissa.value=parts.mantissa;exponent.value=parts.exponent;}editor.dataset.mode="standard";decimal.hidden=true;standard.hidden=false;button.textContent="123";button.title="Use a single number field";button.setAttribute("aria-pressed","true");mantissa.focus();}else{const combined=scaffoldCore.standardValue(mantissa.value,exponent.value);if(combined)decimal.value=combined;editor.dataset.mode="decimal";standard.hidden=true;decimal.hidden=false;button.textContent="×10ⁿ";button.title="Enter this number in standard form";button.setAttribute("aria-pressed","false");decimal.focus();}clearWorkingEditor(editor);}
  function openScaffold(index,manual){const button=elements.questionPanel.querySelector(`[data-scaffold-toggle="${index}"]`),scaffold=document.getElementById(`scaffold-${index}`);if(!button||!scaffold||!scaffold.hidden)return;if(manual&&!session.current.firstSubmitted)mastery.useScaffold(session,index);const row=button.closest(".response-row"),answerLine=row.querySelector(".answer-line"),editor=answerLine.querySelector(".value-entry"),slot=scaffold.querySelector(".scaffold-final-slot");if(slot&&editor){editor.dataset.expected=slot.dataset.expected;editor.dataset.tolerance=slot.dataset.tolerance;editor.classList.add("scaffold-final-entry");slot.insertBefore(editor,slot.querySelector(".working-marker"));answerLine.hidden=true;}scaffold.hidden=false;button.disabled=true;button.setAttribute("aria-expanded","true");save();if(manual)scaffold.querySelector("input:not([hidden])")?.focus();}
  function checkScaffold(button){const scaffold=document.getElementById(`scaffold-${button.dataset.checkScaffold}`),editors=[...scaffold.querySelectorAll("[data-working-editor]")],finalEditor=scaffold.querySelector(".scaffold-final-entry");let correct=0;editors.forEach((editor)=>{const value=workingEditorValue(editor),result=questionCore.markNumber(value,{expected:Number(editor.dataset.expected),tolerance:Number(editor.dataset.tolerance)}),marker=editor.nextElementSibling;editor.classList.remove("working-correct","working-incorrect");if(result.status==="correct"){correct+=1;editor.classList.add("working-correct");marker.textContent="✓";marker.className="working-marker correct";}else{editor.classList.add("working-incorrect");editor.querySelector("input:not([hidden])")?.setAttribute("aria-invalid","true");marker.textContent=value.trim()?"×":"";marker.className="working-marker incorrect";}});if(finalEditor){const index=Number(finalEditor.dataset.responseEditor),result=questionCore.markNumber(responseValue(index),{expected:Number(finalEditor.dataset.expected),tolerance:Number(finalEditor.dataset.tolerance)}),marker=finalEditor.nextElementSibling;finalEditor.classList.remove("working-correct","working-incorrect");if(result.status==="correct"){correct+=1;finalEditor.classList.add("working-correct");marker.textContent="✓";marker.className="working-marker correct";}else{finalEditor.classList.add("working-incorrect");marker.textContent=responseValue(index)?"×":"";marker.className="working-marker incorrect";}}const total=editors.length+(finalEditor?1:0);scaffold.querySelector(".scaffold-feedback").textContent=`${correct}/${total} correct${correct===total?".":" — keep going."}`;}
  function clearResponseMark(index){const row=elements.questionPanel.querySelector(`[data-part="${index}"]`);row.classList.remove("correct","incorrect");row.querySelector(".response-feedback").textContent="";}
  function markResponses(results){results.forEach((result,index)=>{const row=elements.questionPanel.querySelector(`[data-part="${index}"]`);row.classList.remove("correct","incorrect");row.classList.add(result.status==="correct"?"correct":"incorrect");row.querySelector(".response-feedback").textContent=result.status==="correct"?"Correct.":"Check this value.";});}
  function resultSummary(outcome){if(outcome.eligible)return"Mastery evidence secured.";if(outcome.allCorrect)return"Correct, but a scaffold was used. A fresh proof question will return later.";return"Not yet. This calculation will return later with fresh values.";}
  function checkAnswers(){const values=question.responses.map((_,index)=>responseValue(index)),outcome=mastery.submit(session,values),summary=document.getElementById("checkSummary");if(!outcome.accepted){summary.textContent=outcome.reason;return;}markResponses(outcome.results);summary.textContent=outcome.first?resultSummary(outcome):outcome.allCorrect?"All answers are now correct. This does not change the recorded first attempt.":"Keep checking your calculation.";const button=document.getElementById("checkAnswer");button.textContent="Check again";document.getElementById("continueButton").hidden=false;if(outcome.first&&outcome.autoOpen.length){showWorkedAnswer();outcome.autoOpen.forEach((index)=>openScaffold(index,false));}renderGauge();save();}
  function restoreAttempt(){const results=question.responses.map((answer,index)=>questionCore.markNumber(session.current.responses[index]||"",answer));markResponses(results);document.getElementById("checkAnswer").textContent="Check again";document.getElementById("continueButton").hidden=false;document.getElementById("checkSummary").textContent=resultSummary({eligible:session.current.eligible,allCorrect:session.current.firstAllCorrect});if(session.current.workedAvailable)showWorkedAnswer();}

  function renderWorkedPart(lines){return `<div class="worked-block">${workingRows(lines).map((row)=>row.type==="note"?`<p class="math-note">${notationHtml(row.text)}</p>`:`<div class="math-row"><span class="math-lhs">${notationHtml(row.left)}</span><span class="math-equals">=</span><span class="math-rhs">${renderMath(row.right)}</span></div>`).join("")}</div>`;}
  function showWorkedAnswer(){const parts=question.answerParts.length>1?`<ol class="answer-parts">${question.answerParts.map((part)=>`<li class="answer-part">${renderWorkedPart(part)}</li>`).join("")}</ol>`:renderWorkedPart(question.answerParts[0]);elements.answerContent.innerHTML=parts;elements.answerPanel.hidden=false;elements.answerPanel.open=Boolean(session.current.answerRevealed);elements.answerPanel.ontoggle=()=>{if(elements.answerPanel.open){mastery.revealAnswer(session);save();}};}

  function showFinish(){elements.setupScreen.hidden=true;elements.activityScreen.hidden=true;elements.finishScreen.hidden=false;elements.finishGauge.innerHTML=gaugeHtml();elements.finishStats.innerHTML=`<div class="stat"><strong>${session.stats.firstTimeMastered}</strong>First-time mastery</div><div class="stat"><strong>${session.stats.proofQuestions}</strong>Proof questions</div><div class="stat"><strong>${session.stats.scaffolded}</strong>Scaffolded questions</div>`;save();}

  elements.startSession.addEventListener("click",()=>{const selected=[...elements.familyGrid.querySelectorAll("input:checked")].map((input)=>input.value);start(selected);});
  elements.resumeSession.addEventListener("click",resume);
  elements.discardSession.addEventListener("click",()=>{if(confirm("Discard the saved mastery session and start again?")){clearSave();showSetup();}});
  elements.resetSession.addEventListener("click",()=>{if(confirm("Reset all progress for this mastery session?")){clearSave();session=null;showSetup();}});
  elements.newSession.addEventListener("click",()=>{clearSave();session=null;showSetup();});
  showSetup();
})();
