// Generated by scripts/generate_alevel_catalog.js. Edit the curriculum Markdown and activity-links JSON.
(function (root) {
  "use strict";
  root.MASTERS_HIERARCHY = [
  {
    "key": "l6-t1",
    "name": "L6 — Teacher 1",
    "colour": "#55f6ff",
    "topics": [
      [
        1,
        "Atoms, Ions & Compounds",
        [
          "Atomic Structure & Isotopes",
          "Relative Masses",
          "Formulae & Equations"
        ]
      ],
      [
        2,
        "Amount of Substance",
        [
          "Moles & Particles",
          "Empirical & Molecular Formulae",
          "Hydrated Salts",
          "Reacting Masses",
          "Solutions & Concentrations",
          "Gas Calculations",
          "Yield & Atom Economy"
        ]
      ],
      [
        3,
        "Acids & Redox",
        [
          "Acids, Bases & Neutralisation",
          "Standard Solutions & Titrations",
          "Titration Calculations",
          "Oxidation Numbers",
          "Redox Reactions"
        ]
      ],
      [
        4,
        "Periodicity",
        [
          "Periodic Table & Electron Configuration",
          "Ionisation Energies",
          "Metallic Structures",
          "Giant Covalent Structures",
          "Periodic Trends"
        ]
      ],
      [
        5,
        "Group 2",
        [
          "Reactivity Trends",
          "Oxides & Hydroxides",
          "Uses of Group 2 Compounds"
        ]
      ],
      [
        6,
        "Group 7",
        [
          "Halogen Properties",
          "Displacement Reactions",
          "Disproportionation & Chlorine"
        ]
      ],
      [
        7,
        "Chemical Tests",
        [
          "Halide Tests",
          "Carbonate & Sulfate Tests",
          "Ammonium Tests",
          "Identifying Unknown Ions"
        ]
      ],
      [
        8,
        "Enthalpy",
        [
          "Enthalpy Changes & Profiles",
          "Calorimetry",
          "Bond Enthalpies",
          "Hess’s Law"
        ]
      ],
      [
        9,
        "Rates of Reaction",
        [
          "Collision Theory",
          "Rate Graphs & Measurements",
          "Catalysts",
          "Boltzmann Distributions"
        ]
      ],
      [
        10,
        "Equilibrium",
        [
          "Dynamic Equilibrium",
          "Le Chatelier’s Principle",
          "Industrial Conditions",
          "Kc",
          "Kp & Partial Pressures",
          "Equilibrium Calculations",
          "Changing Equilibrium Constants"
        ]
      ]
    ]
  },
  {
    "key": "l6-t2",
    "name": "L6 — Teacher 2",
    "colour": "#54f5b5",
    "topics": [
      [
        1,
        "Electrons & Bonding",
        [
          "Shells, Subshells & Orbitals",
          "Electron Configurations",
          "Ionic Bonding",
          "Covalent & Coordinate Bonding"
        ]
      ],
      [
        2,
        "Molecules",
        [
          "Molecular Shapes & Bond Angles",
          "Electronegativity & Polarity",
          "Intermolecular Forces",
          "Hydrogen Bonding",
          "Simple Molecular Properties"
        ]
      ],
      [
        3,
        "Organic Foundations",
        [
          "Functional Groups & Homologous Series",
          "Naming Organic Compounds",
          "Representing Structures",
          "Structural Isomerism",
          "Bond Fission & Curly Arrows"
        ]
      ],
      [
        4,
        "Alkanes",
        [
          "Structure & Properties",
          "Combustion",
          "Radical Substitution"
        ]
      ],
      [
        5,
        "Alkenes",
        [
          "Double Bonds & Properties",
          "E/Z Isomerism",
          "Addition Reactions",
          "Electrophilic Addition",
          "Addition Polymers & Sustainability"
        ]
      ],
      [
        6,
        "Alcohols",
        [
          "Classification & Properties",
          "Oxidation",
          "Dehydration & Substitution"
        ]
      ],
      [
        7,
        "Haloalkanes",
        [
          "Hydrolysis & Reactivity",
          "Nucleophilic Substitution",
          "Ozone & Halogen Radicals"
        ]
      ],
      [
        8,
        "Organic Synthesis I",
        [
          "Reagents & Conditions",
          "Two-stage Routes",
          "Reflux & Distillation",
          "Separating & Purifying Liquids"
        ]
      ],
      [
        9,
        "Organic Analysis",
        [
          "Mass Spectrometry",
          "Infrared Spectroscopy",
          "Thin-layer Chromatography",
          "Gas Chromatography",
          "Organic Chemical Tests",
          "NMR Principles",
          "Carbon-13 NMR",
          "Proton NMR",
          "Combined Structure Deduction"
        ]
      ]
    ]
  },
  {
    "key": "u6-t1",
    "name": "U6 — Teacher 1",
    "colour": "#ffde59",
    "topics": [
      [
        1,
        "Acids, Bases & pH",
        [
          "Brønsted–Lowry Acids & Bases",
          "Strong Acids & pH",
          "Kw & Strong Bases",
          "Ka & pKa",
          "Weak Acid Calculations",
          "Buffer Action & Uses",
          "Making Buffers",
          "Buffer Calculations",
          "pH Titration Curves",
          "Indicators & pH Measurement"
        ]
      ],
      [
        2,
        "Rate Equations",
        [
          "Orders & Rate Equations",
          "Rate Constants & Units",
          "Concentration–Time & Rate–Concentration Graphs",
          "First-order Half-life",
          "Investigating Rates",
          "Rate-determining Steps",
          "Arrhenius Equation"
        ]
      ],
      [
        3,
        "Thermodynamics",
        [
          "Lattice Enthalpy",
          "Born–Haber Cycles",
          "Solution & Hydration Cycles",
          "Ionic Charge & Radius",
          "Entropy & Dispersal of Energy",
          "Entropy Calculations",
          "Gibbs Free Energy",
          "Temperature & Feasibility"
        ]
      ],
      [
        4,
        "Quantitative Redox",
        [
          "Oxidising & Reducing Agents",
          "Half-equations & Redox Equations",
          "Manganate(VII) Titrations",
          "Iodine–Thiosulfate Titrations"
        ]
      ],
      [
        5,
        "Electrochemistry",
        [
          "Standard Electrode Potentials",
          "Measuring Cell Potentials",
          "Cell Calculations & Feasibility",
          "Storage Cells & Fuel Cells"
        ]
      ]
    ]
  },
  {
    "key": "u6-t2",
    "name": "U6 — Teacher 2",
    "colour": "#d4afff",
    "topics": [
      [
        1,
        "Aromatic",
        [
          "Benzene Structure & Evidence",
          "Naming Aromatic Compounds",
          "Electrophilic Substitution",
          "Phenols",
          "Directing Effects"
        ]
      ],
      [
        2,
        "Aldehydes & Ketones",
        [
          "Carbonyl Structure & Properties",
          "Oxidation & Reduction",
          "Nucleophilic Addition",
          "Carbonyl Tests"
        ]
      ],
      [
        3,
        "Carboxylic Acids & Derivatives",
        [
          "Carboxylic Acid Properties & Reactions",
          "Esterification",
          "Ester Hydrolysis",
          "Acyl Chlorides & Acylation"
        ]
      ],
      [
        4,
        "Amines, Amino Acids & Chirality",
        [
          "Amines & Basicity",
          "Preparing Amines",
          "Amino Acid Reactions",
          "Amides",
          "Optical Isomerism"
        ]
      ],
      [
        5,
        "Condensation Polymers",
        [
          "Polyesters",
          "Polyamides",
          "Polymer Hydrolysis",
          "Monomers & Repeat Units"
        ]
      ],
      [
        6,
        "Organic Synthesis II",
        [
          "Extending Carbon Chains",
          "Nitrile Reactions",
          "Multistep Synthesis",
          "Molecules with Multiple Functional Groups",
          "Preparing & Purifying Solids"
        ]
      ],
      [
        7,
        "Transition Elements",
        [
          "d-block Configurations",
          "Transition-element Properties",
          "Ligands & Coordination",
          "Complex Shapes & Isomerism",
          "Ligand Substitution",
          "Precipitation Reactions",
          "Transition-metal Redox",
          "Identifying Unknown Ions"
        ]
      ]
    ]
  }
];
  root.MASTERS_ACTIVITIES = {
  "l6-t2-1-2": {
    "label": "Electron configurations",
    "href": "activities/electron-configurations/index.html",
    "note": "Choose a level or build mastery across all three levels.",
    "mastery": true
  },
  "u6-t1-1-2": {
    "label": "Acid–base calculations",
    "href": "activities/acid-base-calculations/index.html",
    "note": "Numerical practice for this subtopic. Choose Direct, Linked or Unstructured practice, or build mastery across all three levels.",
    "mastery": true
  },
  "u6-t1-1-3": {
    "label": "Acid–base calculations",
    "href": "activities/acid-base-calculations/index.html",
    "note": "Numerical practice for this subtopic. Choose Direct, Linked or Unstructured practice, or build mastery across all three levels.",
    "mastery": true
  },
  "u6-t1-1-4": {
    "label": "Acid–base calculations",
    "href": "activities/acid-base-calculations/index.html",
    "note": "Numerical practice for this subtopic. Choose Direct, Linked or Unstructured practice, or build mastery across all three levels.",
    "mastery": true
  },
  "u6-t1-1-5": {
    "label": "Acid–base calculations",
    "href": "activities/acid-base-calculations/index.html",
    "note": "Numerical practice for this subtopic. Choose Direct, Linked or Unstructured practice, or build mastery across all three levels.",
    "mastery": true
  },
  "u6-t1-1-7": {
    "label": "Acid–base calculations",
    "href": "activities/acid-base-calculations/index.html",
    "note": "Numerical practice for this subtopic. Choose Direct, Linked or Unstructured practice, or build mastery across all three levels. Calculation practice does not assess practical preparation methods.",
    "mastery": true
  },
  "u6-t1-1-8": {
    "label": "Acid–base calculations",
    "href": "activities/acid-base-calculations/index.html",
    "note": "Numerical practice for this subtopic. Choose Direct, Linked or Unstructured practice, or build mastery across all three levels.",
    "mastery": true
  }
};
  root.MASTERS_DISPLAY = {
  "hiddenGems": [
    "u6-t2-7-1"
  ],
  "redirects": {
    "u6-t2-7-1": "l6-t2-1-2"
  }
};
})(globalThis);
