(function(){
'use strict';
const content=C3L6Content,core=MoleculeCore,marking=C3L6Assessment.create(content,core),$=id=>document.getElementById(id),keys=['a','b','c'];
const storageKey='sjs:c3l6:2012-q2:draft:v1';let state=marking.blank(),editor,restoring=false,introLoaded=false,navigationGeneration=0;
const inspection=new URLSearchParams(location.search).get('inspect')==='c';
if(inspection){state.stage='c';$('saveNotice').textContent='Inspection mode: checks are available in part (c); progress is not saved.';}
else{try{state=marking.restore(JSON.parse(localStorage.getItem(storageKey)));}catch{}}
const canNavigate=key=>inspection||marking.unlocked(state,key);
function save(){if(inspection)return;marking.saveable(state);try{localStorage.setItem(storageKey,JSON.stringify(state));$('saveNotice').textContent='';}catch{$('saveNotice').textContent='Progress cannot be saved in this browser. Keep this page open to retain your work.';}}
function answers(key=state.stage){return content.stages[key].answers;}
function blankDrawing(){return {graph:core.empty(),history:[]};}
function currentDraft(){return state.responses[state.stage][state.selected[state.stage]]||blankDrawing();}
function feedback(){
 const key=state.stage,isAssessment=keys.includes(key);$('checkPart').hidden=inspection||key!=='a'||state.complete.a;$('checkPart').disabled=key==='a'&&(!marking.attempted(state,'a')||state.complete.a);
 $('result').textContent=key==='a'?(state.submitted.a?state.submitted.a.correct+' of '+state.submitted.a.total+' correct'+(state.submitted.a.snapshot!==C3L6Assessment.fingerprint(state.responses.a)?' — answers changed; check again.':'.'):'Complete every answer, then check the whole part.'):'';
 const next=isAssessment&&key!=='c'?keys[keys.indexOf(key)+1]:null,done=key==='a'?state.complete.a:key==='b'?marking.bComplete(state):marking.cComplete(state);
 $('continue').hidden=inspection||!isAssessment||!done||!next;$('continue').textContent=next?'Continue to part ('+next+') →':'Continue';
 $('progressMessage').textContent=!isAssessment?'Introduction and reference · no score.':key==='a'?(done?'Part complete. You can now continue.':'Attempt every answer, then check the whole part.'):(key==='b'?(done?'Part (b) complete. You can now continue.':''):(done?'All three parts complete.':''));
 document.querySelectorAll('[data-stage]').forEach(button=>{const k=button.dataset.stage,locked=!canNavigate(k);button.disabled=!inspection&&(k==='a'?!introLoaded&&!state.complete.a:locked);button.textContent=k==='intro'?'Introduction':'Part ('+k+')'+(locked?' · Locked':(k==='a'?state.complete.a:k==='b'?marking.bComplete(state):marking.cComplete(state))?' · Complete':'');button.setAttribute('aria-pressed',String(k===key));});
 if(key==='b')document.querySelectorAll('.unit-check').forEach(button=>{const id=button.dataset.unit,check=state.unitChecks[id];button.hidden=inspection;button.disabled=inspection||!!check?.passed||!marking.attemptedUnit(state,id);const feedbackNode=document.querySelector('[data-unit-feedback="'+CSS.escape(id)+'"]');feedbackNode.textContent='';updateBoxResults(id,feedbackNode);});
 if(key==='c')updateCFeedback();
}
function updateBoxResults(unitId,announcement){const check=state.unitChecks[unitId],current=!inspection&&check?.snapshot===marking.bUnitSnapshot(state,unitId),results=current?Object.fromEntries(marking.bUnits.find(unit=>unit.id===unitId).slots.map(id=>[id,check.correct===check.total])):{},messages=[];for(const button of document.querySelectorAll('.answer-slot[data-unit="'+unitId+'"]')){const id=button.dataset.answer,marked=Object.hasOwn(results,id),correct=results[id];button.classList.toggle('is-correct',marked&&correct);button.classList.toggle('is-incorrect',marked&&!correct);button.querySelector('.answer-status')?.remove();button.setAttribute('aria-label',(isLocked('b',id)?'View completed structure ':'Edit structure ')+id+(marked?(correct?', correct':', step needs another attempt'):''));if(marked){const badge=document.createElement('span');badge.className='answer-status';badge.setAttribute('aria-hidden','true');badge.textContent=correct?'✓':'?';button.append(badge);messages.push(id+(correct?' correct':' incorrect'));}}announcement.textContent=current?(check.correct===check.total?'Step correct.':'Check this step again.'):'';}
function addClassificationControls(){
 const panel=$('questionPanel');for(const item of answers('a')){const row=panel.querySelector('[data-reaction="'+CSS.escape(item.id)+'"]');if(!row)throw Error('Part (a) question row missing '+item.id);const field=document.createElement('fieldset');field.className='classification-row';field.disabled=state.complete.a;const legend=document.createElement('legend');legend.textContent='Classify reaction '+item.id;field.append(legend);const group=document.createElement('div');group.className='classification-options';for(const choice of ['oxidation','reduction','hydrolysis']){const label=document.createElement('label'),radio=document.createElement('input');radio.type='radio';radio.name='reaction-'+item.id;radio.value=choice;radio.checked=state.responses.a[item.id]===choice;radio.addEventListener('change',()=>{if(state.complete.a)return;state.responses.a[item.id]=choice;save();feedback();});label.append(radio,choice[0].toUpperCase()+choice.slice(1));group.append(label);}field.append(group);row.append(field);}
}
function thumbnail(graph){const svg=editor.depiction(graph),xs=graph.atoms.map(a=>a.x),ys=graph.atoms.map(a=>a.y);if(xs.length){const x=Math.min(...xs)-48,y=Math.min(...ys)-35,w=Math.max(...xs)-x+48,h=Math.max(...ys)-y+35;svg.setAttribute('viewBox',[x,y,w,h].join(' '));}return svg;}
function isLocked(key,id){if(key==='b'){const unit=marking.bUnits.find(item=>item.slots.includes(id)),check=state.unitChecks[unit?.id];return check?.passed===true&&check.snapshot===marking.bUnitSnapshot(state,unit.id);}if(key==='c'){const check=state.slotChecks[id];return check?.correct===true&&check.snapshot===marking.cSnapshot(state,id)&&marking.slotCorrect(state,'c',id);}return false;}
function renderSlots(){
 const key=state.stage;if(key==='a'||key==='intro')return;const host=$('questionPanel');if(key==='b')host.querySelectorAll('.b-step-controls').forEach(node=>node.remove());
 const addSlot=(answer,parent)=>{const button=document.createElement('button'),locked=isLocked(key,answer.id);button.className='answer-slot'+(locked?' is-complete':'');button.dataset.answer=answer.id;if(key==='b')button.dataset.unit=marking.bUnits.find(unit=>unit.slots.includes(answer.id)).id;button.setAttribute('aria-pressed',String(state.selected[key]===answer.id));button.setAttribute('aria-label',(locked?'View completed structure ':'Edit structure ')+answer.label);const label=document.createElement('span');label.className='slot-label';label.textContent=answer.label;const preview=document.createElement('span');preview.className='slot-preview';preview.setAttribute('aria-hidden','true');const graph=state.responses[key][answer.id]?.graph;if(graph?.atoms.length)preview.append(thumbnail(graph));else preview.textContent='Click to draw';button.append(label,preview);button.addEventListener('click',()=>{if(state.selected[key]===answer.id)return;state.selected[key]=answer.id;host.querySelectorAll('[data-answer]').forEach(slot=>slot.setAttribute('aria-pressed',String(slot.dataset.answer===answer.id)));loadDrawing();save();feedback();});parent.append(button);};
 if(key==='b'){
  for(const placeholder of host.querySelectorAll('[data-b-slot]')){const item=answers('b').find(answer=>answer.id===placeholder.dataset.bSlot);placeholder.replaceChildren();placeholder.removeAttribute('role');placeholder.removeAttribute('aria-label');if(placeholder.dataset.coefficient){const coefficient=document.createElement('span');coefficient.className='b-coefficient';coefficient.textContent=placeholder.dataset.coefficient+' ×';placeholder.append(coefficient);}addSlot(item,placeholder);const mass=document.createElement('span');mass.className='digitised-mass';mass.innerHTML='M<sub>r</sub> = '+item.mass;placeholder.append(mass);}
  for(const [index,unit] of marking.bUnits.entries()){const section=document.createElement('div');section.className='b-step-controls';const check=document.createElement('button');check.type='button';check.className='unit-check';check.dataset.unit=unit.id;check.setAttribute('aria-label','Check reaction '+(index<3?['i','ii','iii'][index]:'iv step '+(index-2)));check.textContent='Check';check.addEventListener('click',()=>checkUnit(unit.id));const result=document.createElement('p');result.className='unit-feedback visually-hidden';result.dataset.unitFeedback=unit.id;result.setAttribute('role','status');result.setAttribute('aria-live','polite');section.append(check,result);host.querySelector('[data-step="'+unit.id+'"]').prepend(section);}
 }
 else for(const item of answers('c')){const node=host.querySelector('[data-c-slot="'+item.id+'"]');node.replaceChildren();const check=document.createElement('button');check.type='button';check.className='c-check';check.dataset.checkAnswer=item.id;check.textContent='Check';check.setAttribute('aria-label','Check structure '+item.id);check.addEventListener('click',()=>checkCAnswer(item.id));node.append(check);addSlot(item,node);}
 if(key==='b')renderRepeatedMolecules();
 document.querySelector('.selected-check-row')?.remove();
}
function renderRepeatedMolecules(){for(const node of document.querySelectorAll('[data-b-repeat]')){node.replaceChildren();const id=node.dataset.bRepeat,ready=!!state.responses.b[id]?.graph?.atoms.length;node.classList.toggle('is-ready',ready);const label=document.createElement('span');label.className='repeat-label';label.textContent=id;const drawing=document.createElement('span');drawing.className='repeat-molecule';if(ready)drawing.append(thumbnail(state.responses.b[id].graph));node.append(label,drawing);}}

function refreshThumbnail(){const key=state.stage,host=$('questionPanel');for(const slot of host.querySelectorAll('[data-answer="'+CSS.escape(state.selected[key])+'"] .slot-preview')){slot.replaceChildren();const graph=currentDraft().graph;if(graph.atoms.length)slot.append(thumbnail(graph));else slot.textContent='Click to draw';}if(key==='b')renderRepeatedMolecules();}
function loadDrawing(){const key=state.stage,item=answers().find(a=>a.id===state.selected[key]);if(!item)return;restoring=true;editor.importState(currentDraft());editor.setReadOnly(key==='b'||key==='c'?isLocked(key,item.id):state.complete[key]);restoring=false;$('answerLabel').textContent='Structure '+item.label+(item.mass?' · relative molecular mass '+item.mass:'');$('readOnly').hidden=!(key==='b'||key==='c'?isLocked(key,item.id):state.complete[key]);}
function updateCFeedback(){for(const item of answers('c')){const id=item.id,check=state.slotChecks[id],locked=isLocked('c',id),current=check?.snapshot===marking.cSnapshot(state,id);const node=$('questionPanel').querySelector('[data-c-slot="'+id+'"]'),button=node.querySelector('.answer-slot'),control=node.querySelector('.c-check');control.hidden=false;control.disabled=locked||!marking.attemptedSlot(state,'c',id);button.classList.toggle('is-correct',current&&check.correct);button.classList.toggle('is-incorrect',current&&!check.correct);button.querySelector('.answer-status')?.remove();button.setAttribute('aria-label',(locked?'View completed structure ':'Edit structure ')+id+(current?(check.correct?', correct':', try again'):''));if(current){const badge=document.createElement('span');badge.className='answer-status';badge.setAttribute('aria-hidden','true');badge.textContent=check.correct?'✓':'?';button.append(badge);}}}
function checkCAnswer(id){editor.cancelGesture();const result=marking.checkCSlot(state,id,{allowLocked:inspection});if(!result)return;save();renderSlots();loadDrawing();feedback();$('announcement').textContent=id+(result.correct?' correct.':' Try again.');}
function checkUnit(id){if(inspection)return;editor.cancelGesture();const result=marking.checkUnit(state,id);if(!result)return;save();renderSlots();const selected=state.selected.b;if(isLocked('b',selected))loadDrawing();feedback();}
async function loadPanel(key,generation){const panel=$(key==='intro'?'panel-intro':'questionPanel');if(generation!==navigationGeneration)return;panel.replaceChildren();$('panelError').hidden=true;try{const response=await fetch('panels/'+key+'.html',{cache:'no-cache'});if(!response.ok)throw Error('HTTP '+response.status);const markup=await response.text();if(generation!==navigationGeneration)return;const parsed=new DOMParser().parseFromString(markup,'text/html'),base=new URL('panels/'+key+'.html',location.href);for(const el of parsed.querySelectorAll('[src],[href],[poster]'))for(const attr of ['src','href','poster'])if(el.hasAttribute(attr))el.setAttribute(attr,new URL(el.getAttribute(attr),base).href);if(generation!==navigationGeneration)return;panel.replaceChildren(...Array.from(parsed.body.childNodes).map(node=>document.importNode(node,true)));if(key==='a')addClassificationControls();if(key==='intro')introLoaded=true;}catch(error){if(generation!==navigationGeneration)return;console.error('Could not load C3L6 panel',key,error);if(key==='intro'){introLoaded=false;panel.textContent='Introduction content is unavailable. Reload this activity to continue.';}else $('panelError').hidden=false;}}
async function renderStage(){const generation=++navigationGeneration,key=state.stage,isIntro=key==='intro';$('introView').hidden=!isIntro;$('startQuestions').hidden=false;$('question').classList.toggle('visually-hidden',key!=='intro');$('question').textContent=key==='a'?'Part (a)':key==='b'?'Part (b)':key==='c'?'Part (c)':'';$('stageEyebrow').textContent=isIntro?'INTRODUCTION':'PART ('+key+')';$('partNumber').innerHTML=isIntro?'— <span>/ 03</span>':'0'+(keys.indexOf(key)+1)+' <span>/ 03</span>';document.querySelector('.exercise').hidden=isIntro;$('classifications').hidden=key!=='a';$('drawingSection').hidden=key==='a'||isIntro;if(isIntro){introLoaded=false;$('startQuestions').disabled=true;$('panel-intro').replaceChildren();await loadPanel('intro',generation);if(generation!==navigationGeneration)return;$('startQuestions').disabled=!introLoaded;}else{await loadPanel(key,generation);if(generation!==navigationGeneration)return;if(key!=='a'){renderSlots();loadDrawing();}}if(generation!==navigationGeneration)return;feedback();save();}
editor=createMoleculeEditor({root:$('drawingSection'),drawingScale:()=>['b','c'].includes(state.stage)?.55:1,announcement:$('announcement'),onViewChange:()=>{if(editor&&state.stage!=='a'&&state.stage!=='intro')renderSlots();}});
editor.onChange(()=>{if(restoring||state.stage==='a'||state.stage==='intro'||isLocked(state.stage,state.selected[state.stage]))return;state.responses[state.stage][state.selected[state.stage]]=editor.exportState();refreshThumbnail();feedback();save();});
$('checkPart').addEventListener('click',()=>{if(inspection||state.stage!=='a')return;editor.cancelGesture();const result=marking.submit(state,'a');if(!result)return;save();feedback();if(state.complete.a)$('questionPanel').querySelectorAll('.classification-row').forEach(row=>row.disabled=true);});
async function navigate(key){if(!canNavigate(key)||!inspection&&key==='a'&&!introLoaded&&!state.complete.a)return;editor.cancelGesture();state.stage=key;await renderStage();if(key===state.stage){document.querySelector('[data-stage="'+key+'"]').focus({preventScroll:true});window.scrollTo({top:0,left:0,behavior:'instant'});}}
document.querySelectorAll('[data-stage]').forEach(button=>button.addEventListener('click',()=>navigate(button.dataset.stage)));$('startQuestions').addEventListener('click',()=>navigate('a'));$('continue').addEventListener('click',()=>{if(state.stage==='a'&&state.complete.a)navigate('b');else if(state.stage==='b'&&marking.bComplete(state))navigate('c');});$('restart').addEventListener('click',()=>$('restartDialog').showModal());$('cancelRestart').addEventListener('click',()=>$('restartDialog').close());$('confirmRestart').addEventListener('click',()=>{$('restartDialog').close();editor.cancelGesture();state=marking.blank();renderStage();});window.addEventListener('pagehide',save);renderStage();
})();
