(function(){
'use strict';
const content=C3L6Content,core=MoleculeCore,marking=C3L6Assessment.create(content,core),$=id=>document.getElementById(id),keys=['a','b','c'];
const storageKey='sjs:c3l6:2012-q2:draft:v1';let state=marking.blank(),editor,restoring=false,introLoaded=false,navigationGeneration=0;
const inspection=new URLSearchParams(location.search).get('inspect')==='c';
if(inspection){state.stage='c';$('saveNotice').textContent='Inspection mode: progress is not saved and parts are not marked complete.';}
else{try{state=marking.restore(JSON.parse(localStorage.getItem(storageKey)));}catch{}}
const canNavigate=key=>inspection||marking.unlocked(state,key);
function save(){if(inspection)return;marking.saveable(state);try{localStorage.setItem(storageKey,JSON.stringify(state));$('saveNotice').textContent='';}catch{$('saveNotice').textContent='Progress cannot be saved in this browser. Keep this page open to retain your work.';}}
function answers(key=state.stage){return content.stages[key].answers;}
function blankDrawing(){return {graph:core.empty(),history:[]};}
function currentDraft(){return state.responses[state.stage][state.selected[state.stage]]||blankDrawing();}
function getCheckRow(){let row=document.querySelector('.selected-check-row');if(!row){row=document.createElement('div');row.className='selected-check-row';row.innerHTML='<button id="checkSelected" class="primary">Check selected structure</button><p id="selectedResult" role="status" aria-live="polite"></p>';document.querySelector('.editor-heading').before(row);$('checkSelected').addEventListener('click',checkSelected);}return row;}
function feedback(){
 const key=state.stage,isAssessment=keys.includes(key);$('checkPart').hidden=inspection||key!=='a'||state.complete.a;$('checkPart').disabled=key==='a'&&(!marking.attempted(state,'a')||state.complete.a);
 $('result').textContent=key==='a'?(state.submitted.a?state.submitted.a.correct+' of '+state.submitted.a.total+' correct'+(state.submitted.a.snapshot!==C3L6Assessment.fingerprint(state.responses.a)?' — answers changed; check again.':'.'):'Complete every answer, then check the whole part.'):'Only the selected molecule or step is checked.';
 const next=isAssessment&&key!=='c'?keys[keys.indexOf(key)+1]:null,done=key==='a'?state.complete.a:key==='b'?marking.bComplete(state):marking.cComplete(state);
 $('continue').hidden=inspection||!isAssessment||!done||!next;$('continue').textContent=next?'Continue to part ('+next+') →':'Continue';
 $('progressMessage').textContent=!isAssessment?'Introduction and reference · no score.':key==='a'?(done?'Part complete. You can now continue.':'Attempt every answer, then check the whole part.'):(key==='b'?(done?'Part (b) complete. You can now continue.':'Check each reaction step after drawing all its product slots.'):(done?'All three parts complete.':'Check each molecule as you draw it.'));
 document.querySelectorAll('[data-stage]').forEach(button=>{const k=button.dataset.stage,locked=!canNavigate(k);button.disabled=!inspection&&(k==='a'?!introLoaded&&!state.complete.a:locked);button.textContent=k==='intro'?'Introduction':'Part ('+k+')'+(locked?' · Locked':(k==='a'?state.complete.a:k==='b'?marking.bComplete(state):marking.cComplete(state))?' · Complete':'');button.setAttribute('aria-pressed',String(k===key));});
 if(key==='b')document.querySelectorAll('.unit-check').forEach(button=>{const id=button.dataset.unit,check=state.unitChecks[id];button.hidden=inspection;button.disabled=inspection||!!check?.passed||!marking.attemptedUnit(state,id);const feedbackNode=document.querySelector('[data-unit-feedback="'+CSS.escape(id)+'"]');feedbackNode.textContent=check?check.correct+' of '+check.total+' correct'+(check.snapshot!==marking.bUnitSnapshot(state,id)?' — answers changed; check again.':check.passed?' · Complete.':' · Check again when ready.'):'Draw every output in this step, then check.';});
 if(key==='c')updateSelectedFeedback();
}
function addClassificationControls(){
 const panel=$('questionPanel');for(const item of answers('a')){const row=panel.querySelector('[data-reaction="'+CSS.escape(item.id)+'"]');if(!row)throw Error('Part (a) question row missing '+item.id);const field=document.createElement('fieldset');field.className='classification-row';field.disabled=state.complete.a;const legend=document.createElement('legend');legend.textContent='Classify reaction '+item.id;field.append(legend);const group=document.createElement('div');group.className='classification-options';for(const choice of ['oxidation','reduction','hydrolysis']){const label=document.createElement('label'),radio=document.createElement('input');radio.type='radio';radio.name='reaction-'+item.id;radio.value=choice;radio.checked=state.responses.a[item.id]===choice;radio.addEventListener('change',()=>{if(state.complete.a)return;state.responses.a[item.id]=choice;save();feedback();});label.append(radio,choice[0].toUpperCase()+choice.slice(1));group.append(label);}field.append(group);row.append(field);}
}
function thumbnail(graph){const svg=editor.depiction(graph),xs=graph.atoms.map(a=>a.x),ys=graph.atoms.map(a=>a.y);if(xs.length){const x=Math.min(...xs)-48,y=Math.min(...ys)-35,w=Math.max(...xs)-x+48,h=Math.max(...ys)-y+35;svg.setAttribute('viewBox',[x,y,w,h].join(' '));}return svg;}
function isLocked(key,id){if(key==='b'){const unit=marking.bUnits.find(item=>item.slots.includes(id)),check=state.unitChecks[unit?.id];return check?.passed===true&&check.snapshot===marking.bUnitSnapshot(state,unit.id);}if(key==='c'){const check=state.slotChecks[id];return check?.correct===true&&check.snapshot===marking.cSnapshot(state,id)&&marking.slotCorrect(state,'c',id);}return false;}
function renderSlots(){
 const key=state.stage;if(key==='a'||key==='intro')return;const host=$('answerSlots');host.replaceChildren();
 const addSlot=(answer,parent)=>{const button=document.createElement('button'),locked=isLocked(key,answer.id);button.className='answer-slot'+(locked?' is-complete':'');button.dataset.answer=answer.id;if(key==='b')button.dataset.unit=marking.bUnits.find(unit=>unit.slots.includes(answer.id)).id;button.setAttribute('aria-pressed',String(state.selected[key]===answer.id));button.setAttribute('aria-label',(locked?'View completed structure ':'Edit structure ')+answer.label);const label=document.createElement('span');label.className='slot-label';label.textContent=answer.label;const preview=document.createElement('span');preview.className='slot-preview';preview.setAttribute('aria-hidden','true');const graph=state.responses[key][answer.id]?.graph;if(graph?.atoms.length)preview.append(thumbnail(graph));else preview.textContent='Draw';button.append(label,preview);button.addEventListener('click',()=>{if(state.selected[key]===answer.id)return;state.selected[key]=answer.id;host.querySelectorAll('[data-answer]').forEach(slot=>slot.setAttribute('aria-pressed',String(slot.dataset.answer===answer.id)));loadDrawing();save();feedback();});parent.append(button);};
 if(key==='b'){for(const [index,unit] of marking.bUnits.entries()){const section=document.createElement('section');section.className='answer-unit';section.dataset.unit=unit.id;section.setAttribute('aria-labelledby','unit-heading-'+unit.id);const heading=document.createElement('h3');heading.id='unit-heading-'+unit.id;heading.className='answer-unit-title';heading.textContent=index<3?'Reaction ('+['i','ii','iii'][index]+')':'Reaction (iv) · step '+(index-2);const slots=document.createElement('div');slots.className='answer-unit-slots';for(const id of unit.slots)addSlot(answers('b').find(item=>item.id===id),slots);const check=document.createElement('button');check.type='button';check.className='unit-check';check.dataset.unit=unit.id;check.dataset.step=unit.id;check.setAttribute('aria-label','Check '+heading.textContent);check.textContent='Check step';check.hidden=inspection;check.disabled=inspection||!!state.unitChecks[unit.id]?.passed||!marking.attemptedUnit(state,unit.id);check.addEventListener('click',()=>checkUnit(unit.id));const result=document.createElement('p');result.className='unit-feedback';result.dataset.unitFeedback=unit.id;result.setAttribute('role','status');result.setAttribute('aria-live','polite');section.append(heading,slots,check,result);host.append(section);}}
 else for(const item of answers(key))addSlot(item,host);
 if(key==='c')getCheckRow();else $('.selected-check-row')?.remove();
}
function refreshThumbnail(){const key=state.stage,slot=$('answerSlots').querySelector('[data-answer="'+CSS.escape(state.selected[key])+'"] .slot-preview');if(!slot)return;slot.replaceChildren();const graph=currentDraft().graph;if(graph.atoms.length)slot.append(thumbnail(graph));else slot.textContent='Draw';}
function loadDrawing(){const key=state.stage,item=answers().find(a=>a.id===state.selected[key]);if(!item)return;restoring=true;editor.importState(currentDraft());editor.setReadOnly(key==='b'||key==='c'?isLocked(key,item.id):state.complete[key]);restoring=false;$('answerLabel').textContent='Structure '+item.label+(item.mass?' · relative molecular mass '+item.mass:'');$('readOnly').hidden=!(key==='b'||key==='c'?isLocked(key,item.id):state.complete[key]);}
function updateSelectedFeedback(){if(state.stage!=='c')return;const id=state.selected.c,check=state.slotChecks[id],snapshot=marking.cSnapshot(state,id),locked=isLocked('c',id);$('checkSelected').hidden=inspection||locked;$('checkSelected').disabled=inspection||locked||!marking.attemptedSlot(state,'c',id);$('selectedResult').textContent=check?(check.snapshot!==snapshot?'Structure changed; check again.':check.correct?'Correct.':'Incorrect.'):'Draw the selected molecule, then check it.';}
function checkSelected(){if(inspection)return;editor.cancelGesture();const result=marking.checkCSlot(state,state.selected.c);if(!result)return;save();renderSlots();loadDrawing();feedback();}
function checkUnit(id){if(inspection)return;editor.cancelGesture();const result=marking.checkUnit(state,id);if(!result)return;save();renderSlots();const selected=state.selected.b;if(isLocked('b',selected))loadDrawing();feedback();}
async function loadPanel(key,generation){const panel=$(key==='intro'?'panel-intro':'questionPanel');if(generation!==navigationGeneration)return;panel.replaceChildren();$('panelError').hidden=true;try{const response=await fetch('panels/'+key+'.html');if(!response.ok)throw Error('HTTP '+response.status);const markup=await response.text();if(generation!==navigationGeneration)return;const parsed=new DOMParser().parseFromString(markup,'text/html'),base=new URL('panels/'+key+'.html',location.href);for(const el of parsed.querySelectorAll('[src],[href],[poster]'))for(const attr of ['src','href','poster'])if(el.hasAttribute(attr))el.setAttribute(attr,new URL(el.getAttribute(attr),base).href);if(generation!==navigationGeneration)return;panel.replaceChildren(...Array.from(parsed.body.childNodes).map(node=>document.importNode(node,true)));if(key==='a')addClassificationControls();if(key==='intro')introLoaded=true;}catch(error){if(generation!==navigationGeneration)return;console.error('Could not load C3L6 panel',key,error);if(key==='intro'){introLoaded=false;panel.textContent='Introduction content is unavailable. Reload this activity to continue.';}else $('panelError').hidden=false;}}
async function renderStage(){const generation=++navigationGeneration,key=state.stage,isIntro=key==='intro';$('introView').hidden=!isIntro;$('startQuestions').hidden=false;$('question').textContent=key==='a'?'Part (a)':key==='b'?'Part (b)':key==='c'?'Part (c)':'';$('stageEyebrow').textContent=isIntro?'INTRODUCTION':'PART ('+key+')';$('partNumber').innerHTML=isIntro?'— <span>/ 03</span>':'0'+(keys.indexOf(key)+1)+' <span>/ 03</span>';document.querySelector('.exercise').hidden=isIntro;$('classifications').hidden=key!=='a';$('drawingSection').hidden=key==='a'||isIntro;if(isIntro){introLoaded=false;$('startQuestions').disabled=true;$('panel-intro').replaceChildren();await loadPanel('intro',generation);if(generation!==navigationGeneration)return;$('startQuestions').disabled=!introLoaded;}else{await loadPanel(key,generation);if(generation!==navigationGeneration)return;if(key!=='a'){renderSlots();loadDrawing();}}if(generation!==navigationGeneration)return;feedback();save();}
editor=createMoleculeEditor({root:$('drawingSection'),announcement:$('announcement'),onViewChange:()=>{if(editor&&state.stage!=='a'&&state.stage!=='intro')renderSlots();}});
editor.onChange(()=>{if(restoring||state.stage==='a'||state.stage==='intro'||isLocked(state.stage,state.selected[state.stage]))return;state.responses[state.stage][state.selected[state.stage]]=editor.exportState();refreshThumbnail();feedback();save();});
$('checkPart').addEventListener('click',()=>{if(inspection||state.stage!=='a')return;editor.cancelGesture();const result=marking.submit(state,'a');if(!result)return;save();feedback();if(state.complete.a)$('questionPanel').querySelectorAll('.classification-row').forEach(row=>row.disabled=true);});
async function navigate(key){if(!canNavigate(key)||!inspection&&key==='a'&&!introLoaded&&!state.complete.a)return;editor.cancelGesture();state.stage=key;await renderStage();if(key===state.stage&&key!=='intro'){$('question').focus({preventScroll:true});$('question').scrollIntoView({block:'start',behavior:'smooth'});}}
document.querySelectorAll('[data-stage]').forEach(button=>button.addEventListener('click',()=>navigate(button.dataset.stage)));$('startQuestions').addEventListener('click',()=>navigate('a'));$('continue').addEventListener('click',()=>{if(state.stage==='a'&&state.complete.a)navigate('b');else if(state.stage==='b'&&marking.bComplete(state))navigate('c');});$('restart').addEventListener('click',()=>$('restartDialog').showModal());$('cancelRestart').addEventListener('click',()=>$('restartDialog').close());$('confirmRestart').addEventListener('click',()=>{$('restartDialog').close();editor.cancelGesture();state=marking.blank();renderStage();});window.addEventListener('pagehide',save);renderStage();
})();
